server:
  port: 9192
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "lephilong1902@gmail.com"
    password: "tchf ismo zcqw lxng"
    properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"