@startsalt
{
    ..
    == USERS table
    {T!
        + user_id | username | email | password | created_at | updated_at
        + u01 | khuongvo2105 | khuongvo2105@gmail.com | *** | ... | ...
        + u02 | nguyenvo0909 | nguyenvo0909@gmail.com | *** | ... | ...
        + u03 | khuongvo | 21130407@gmail.com | *** | ... | ...
        + u04 | lelongphi | lephilong@gmail.com | *** | ... | ...
        + u05 | ainhung | ainhung@gmail.com | *** | ... | ...
    }
    ..
    == POSTS table
    {T!
        + post_id | user_id | caption | created_at | updated_at
        + 1 | u01 | "This is my first post!" | ... | ...
        + 2 | u01 | "This is my second post!" | ... | ...
        + 3 | u02 | "This is my first post! From NguyenVo0909" | ... | ...
        + 4 | u01 | "This is my third post!" | ... | ...
        + 5 | u04 | "Hello everyone!" | ... | ...
    }
    ..
    == COMMENTS table
    {T!
        + comment_id | user_id | post_id | comment_text | created_at
        + 1 | u01 | 1 | "u01 said:..." | ...
        + 2 | u02 | 1 | "u02 reply u01:..." | ...
        + 3 | u03 | 2 | "u03 said:..." | ...
        + 4 | u03 | 4 | "u03 reacted:..." | ...
        + 5 | u05 | 4 | "u05 sent react:..." | ...
    }

    ..
    == LIKES table
    {T!
        + like_id | user_id | post_id | created_at
        + 1 | u01 | 1 | ...
        + 2 | u01 | 2 | ...
        + 3 | u01 | 3 | ...
        + 4 | u01 | 4 | ...
        + 5 | u01 | 5 | ...
        + 6 | u02 | 1 | ...
        + 7 | u02 | 4 | ...
        + 8 | u05 | 5 | ...
        + 9 | u03 | 5 | ...
        + 10 | u04 | 5 | ...
    }
    ..
    == MEDIAS table
    {T!
        + media_id | post_id | media_url | created_at
        + 1 | 1 | https://img | ...
        + 2 | 1 | https://img | ...
        + 3 | 1 | https://img | ...
        + 4 | 3 | https://video | ...
        + 5 | 4 | https://img | ...
        + 6 | 2 | https://img | ...
        + 7 | 5 | https://img | ...
    }
    ..
    == FOLLOWS table
   {T!
        + follow_id | follower_user_id | following_user_id | created_at
        + 1 | u01 | u02 | ...
        + 2 | u01 | u03 | ...
        + 3 | u01 | u04 | ...
        + 4 | u02 | u01 | ...
        + 5 | u03 | u04 | ...
        + 6 | u03 | u05 | ...
        + 7 | u03 | u01 | ...
        + 8 | u05 | u02 | ...
   }
    ..
    == INNER JOIN (USERS, POSTS)
    {
        T!
         
    }
}
@endsalt