server:
  port: 8080
  servlet:
    context-path: /chat-application
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/Chat_Application"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: "lephilong1902@gmail.com"
    password: "tchf ismo zcqw lxng"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  signerKey: "CQi5Od7TCiOp6gLgEaj6niGw6ZRxqbS3V06hTRX5V5wwbGkQGPv2fMMTEOGe2COg\n"
